title: "Eric Brandwein"
description: "Computer Scientist"
author:
  name: "Eric Brandwein"
  affiliation: "Departamento de Computaci√≥n, FCEyN, Universidad de Buenos Aires, Buenos Aires, Argentina"
  email: "ebrandwein@dc.uba.ar"
  orcid: "0009-0003-2559-7173"
baseurl: "" # the subpath of your site, e.g. /repo-name
url: "" # the base hostname & protocol for your site
remote_theme: "pages-themes/dinky@v0.2.0"
markdown: kramdown
plugins:
  - jekyll-remote-theme

nav:
  - name: "Home"
    link: "/"
  - name: "Studies"
    link: "/studies/"
  - name: "Publications"
    link: "/publications/"
  - name: "Talks"
    link: "/talks/"
  - name: "Conferences"
    link: "/conferences/"
  - name: "Students"
    link: "/students/"
  - name: "CV"
    link: "/cv/"
  - name: "Teaching"
    link: "/teaching/"
  - name: "Awards"
    link: "/awards/"
