title: "Researcher â€” Eric Brandwein"
description: "Academic webpage for research, publications, and contact info. Customize with your details."
author:
  name: "Eric Brandwein"
  affiliation: "Departamento de computacion, UBA"
  email: "your.email@example.com"
  orcid: "0000-0000-0000-0000"
baseurl: "" # the subpath of your site, e.g. /repo-name
url: "" # the base hostname & protocol for your site
remote_theme: "pages-themes/dinky@v0.2.0"
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one


nav:
  - name: "Home"
    link: "/"
  - name: "Studies"
    link: "/studies/"
  - name: "Publications"
    link: "/publications/"
  - name: "Talks"
    link: "/talks/"
  - name: "Conferences"
    link: "/conferences/"
  - name: "Students"
    link: "/students/"
  - name: "CV"
    link: "/cv/"
  - name: "Teaching"
    link: "/teaching/"
  - name: "Awards"
    link: "/awards/"

email: "your.email@example.com"
orcid: "0000-0000-0000-0000"
